<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AutoBuyer.TelegramIngestion.Worker</UserSecretsId>
    <AppDesignerFolder>Properties</AppDesignerFolder>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.18" />
    <PackageReference Include="WTelegramClient" Version="4.4.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoBuyer.Application\AutoBuyer.Application.csproj" />
    <ProjectReference Include="..\AutoBuyer.Infrastructure\AutoBuyer.Infrastructure.csproj" />
  </ItemGroup>

</Project>
